/**
 * High-quality demo/sandbox data for showcasing the product.
 * Used as fallback when the database has no real data.
 */

import type { Tables } from "@/integrations/supabase/types";

type Interaction = Tables<"interactions">;
type Review = Tables<"reviews">;
type Stream = Tables<"streams">;

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();

// ─── DEMO INTERACTIONS ──────────────────────────────────────────
export const DEMO_INTERACTIONS: Interaction[] = [
  {
    id: "demo-int-1",
    user_id: "demo",
    content: "Hey — do you guys ship to Vancouver? I've been eyeing the new collection!",
    author_name: "Rachel Kim",
    author_handle: "@rachelkim_",
    author_avatar: null,
    platform: "instagram",
    interaction_type: "comment",
    sentiment: "neutral",
    sentiment_score: 0.5,
    status: "pending",
    urgency_score: 3,
    post_url: null,
    external_id: null,
    response: null,
    responded_at: null,
    metadata: null,
    parent_interaction_id: null,
    assigned_to: null,
    reply_count: 0,
    resolved: false,
    resolved_at: null,
    resolved_by: null,
    created_at: hoursAgo(0.03),
    updated_at: hoursAgo(0.03),
  },
  {
    id: "demo-int-2",
    user_id: "demo",
    content: "Order #4821 still hasn't arrived. It's been 9 days now and tracking hasn't updated since last Tuesday.",
    author_name: "Tom Nguyen",
    author_handle: null,
    author_avatar: null,
    platform: "google",
    interaction_type: "review",
    sentiment: "negative",
    sentiment_score: 0.15,
    status: "pending",
    urgency_score: 9,
    post_url: null,
    external_id: null,
    response: null,
    responded_at: null,
    metadata: null,
    parent_interaction_id: null,
    assigned_to: null,
    reply_count: 0,
    resolved: false,
    resolved_at: null,
    resolved_by: null,
    created_at: hoursAgo(0.23),
    updated_at: hoursAgo(0.23),
  },
  {
    id: "demo-int-3",
    user_id: "demo",
    content: "Honestly impressed with the quality. Packaging was beautiful too — felt like opening a gift 🎁",
    author_name: "Priya Sharma",
    author_handle: null,
    author_avatar: null,
    platform: "google",
    interaction_type: "review",
    sentiment: "positive",
    sentiment_score: 0.92,
    status: "pending",
    urgency_score: 1,
    post_url: null,
    external_id: null,
    response: null,
    responded_at: null,
    metadata: null,
    parent_interaction_id: null,
    assigned_to: null,
    reply_count: 0,
    resolved: false,
    resolved_at: null,
    resolved_by: null,
    created_at: hoursAgo(1),
    updated_at: hoursAgo(1),
  },
  {
    id: "demo-int-4",
    user_id: "demo",
    content: "This isn't what I ordered — can someone help? I got the wrong size and color.",
    author_name: "Jordan Ellis",
    author_handle: "@jordanellis",
    author_avatar: null,
    platform: "facebook",
    interaction_type: "comment",
    sentiment: "negative",
    sentiment_score: 0.2,
    status: "pending",
    urgency_score: 7,
    post_url: null,
    external_id: null,
    response: null,
    responded_at: null,
    metadata: null,
    parent_interaction_id: null,
    assigned_to: null,
    reply_count: 0,
    resolved: false,
    resolved_at: null,
    resolved_by: null,
    created_at: hoursAgo(2),
    updated_at: hoursAgo(2),
  },
  {
    id: "demo-int-5",
    user_id: "demo",
    content: "Just placed my third order this month. You guys have completely replaced my old go-to brand 💯",
    author_name: "Marcus Chen",
    author_handle: "@marcuschen",
    author_avatar: null,
    platform: "instagram",
    interaction_type: "mention",
    sentiment: "positive",
    sentiment_score: 0.95,
    status: "responded",
    urgency_score: 1,
    post_url: null,
    external_id: null,
    response: "Thank you Marcus! That means the world to us. We're so glad you love our products! 🙏",
    responded_at: hoursAgo(2.5),
    metadata: null,
    parent_interaction_id: null,
    assigned_to: null,
    reply_count: 1,
    resolved: true,
    resolved_at: hoursAgo(2.5),
    resolved_by: null,
    created_at: hoursAgo(3),
    updated_at: hoursAgo(2.5),
  },
  {
    id: "demo-int-6",
    user_id: "demo",
    content: "How do I change my subscription plan? Can't find it in the settings anywhere.",
    author_name: "Sarah Mitchell",
    author_handle: "@sarahmitchell",
    author_avatar: null,
    platform: "twitter",
    interaction_type: "dm",
    sentiment: "neutral",
    sentiment_score: 0.45,
    status: "pending",
    urgency_score: 4,
    post_url: null,
    external_id: null,
    response: null,
    responded_at: null,
    metadata: null,
    parent_interaction_id: null,
    assigned_to: null,
    reply_count: 0,
    resolved: false,
    resolved_at: null,
    resolved_by: null,
    created_at: hoursAgo(4),
    updated_at: hoursAgo(4),
  },
  {
    id: "demo-int-7",
    user_id: "demo",
    content: "Your team went above and beyond to fix my issue. Seriously the best customer service I've experienced.",
    author_name: "David Park",
    author_handle: null,
    author_avatar: null,
    platform: "google",
    interaction_type: "review",
    sentiment: "positive",
    sentiment_score: 0.98,
    status: "responded",
    urgency_score: 1,
    post_url: null,
    external_id: null,
    response: "David, thank you for the kind words! We're thrilled we could help. Don't hesitate to reach out anytime!",
    responded_at: hoursAgo(5),
    metadata: null,
    parent_interaction_id: null,
    assigned_to: null,
    reply_count: 1,
    resolved: true,
    resolved_at: hoursAgo(5),
    resolved_by: null,
    created_at: hoursAgo(6),
    updated_at: hoursAgo(5),
  },
  {
    id: "demo-int-8",
    user_id: "demo",
    content: "Love the new product line! When will the summer collection drop? 🌴",
    author_name: "Emma Rodriguez",
    author_handle: "@emmarodriguez",
    author_avatar: null,
    platform: "instagram",
    interaction_type: "comment",
    sentiment: "positive",
    sentiment_score: 0.88,
    status: "pending",
    urgency_score: 2,
    post_url: null,
    external_id: null,
    response: null,
    responded_at: null,
    metadata: null,
    parent_interaction_id: null,
    assigned_to: null,
    reply_count: 0,
    resolved: false,
    resolved_at: null,
    resolved_by: null,
    created_at: hoursAgo(8),
    updated_at: hoursAgo(8),
  },
  {
    id: "demo-int-9",
    user_id: "demo",
    content: "Terrible experience. Product broke after 2 days. I want a full refund immediately.",
    author_name: "Alex Johnson",
    author_handle: null,
    author_avatar: null,
    platform: "facebook",
    interaction_type: "review",
    sentiment: "negative",
    sentiment_score: 0.05,
    status: "escalated",
    urgency_score: 10,
    post_url: null,
    external_id: null,
    response: null,
    responded_at: null,
    metadata: null,
    parent_interaction_id: null,
    assigned_to: null,
    reply_count: 0,
    resolved: false,
    resolved_at: null,
    resolved_by: null,
    created_at: hoursAgo(10),
    updated_at: hoursAgo(10),
  },
  {
    id: "demo-int-10",
    user_id: "demo",
    content: "Can you send me the care instructions for the silk blend? Forgot to save them.",
    author_name: "Nina Patel",
    author_handle: "@ninapatel",
    author_avatar: null,
    platform: "instagram",
    interaction_type: "dm",
    sentiment: "neutral",
    sentiment_score: 0.5,
    status: "responded",
    urgency_score: 2,
    post_url: null,
    external_id: null,
    response: "Hi Nina! Of course — hand wash cold, lay flat to dry. Avoid direct heat. Full guide: socialrep.ai/care",
    responded_at: hoursAgo(11),
    metadata: null,
    parent_interaction_id: null,
    assigned_to: null,
    reply_count: 1,
    resolved: true,
    resolved_at: hoursAgo(11),
    resolved_by: null,
    created_at: hoursAgo(12),
    updated_at: hoursAgo(11),
  },
  {
    id: "demo-int-11",
    user_id: "demo",
    content: "Saw you guys at the trade show last week — amazing booth! Will you be at the expo next month too?",
    author_name: "Chris Yang",
    author_handle: "@chrisyang",
    author_avatar: null,
    platform: "linkedin",
    interaction_type: "mention",
    sentiment: "positive",
    sentiment_score: 0.82,
    status: "pending",
    urgency_score: 2,
    post_url: null,
    external_id: null,
    response: null,
    responded_at: null,
    metadata: null,
    parent_interaction_id: null,
    assigned_to: null,
    reply_count: 0,
    resolved: false,
    resolved_at: null,
    resolved_by: null,
    created_at: hoursAgo(18),
    updated_at: hoursAgo(18),
  },
  {
    id: "demo-int-12",
    user_id: "demo",
    content: "Your website says 'in stock' but I can't add it to cart. Bug?",
    author_name: "Lisa Wong",
    author_handle: "@lisawong",
    author_avatar: null,
    platform: "twitter",
    interaction_type: "mention",
    sentiment: "negative",
    sentiment_score: 0.3,
    status: "pending",
    urgency_score: 6,
    post_url: null,
    external_id: null,
    response: null,
    responded_at: null,
    metadata: null,
    parent_interaction_id: null,
    assigned_to: null,
    reply_count: 0,
    resolved: false,
    resolved_at: null,
    resolved_by: null,
    created_at: hoursAgo(22),
    updated_at: hoursAgo(22),
  },
  // Add some older interactions for chart data
  ...Array.from({ length: 20 }, (_, i) => ({
    id: `demo-int-old-${i}`,
    user_id: "demo",
    content: `Sample interaction ${i + 1} for analytics data.`,
    author_name: `User ${i + 1}`,
    author_handle: null,
    author_avatar: null,
    platform: (["instagram", "google", "facebook", "twitter", "linkedin"] as const)[i % 5],
    interaction_type: (["comment", "review", "dm", "mention"] as const)[i % 4],
    sentiment: (["positive", "neutral", "negative"] as const)[i % 3],
    sentiment_score: Math.random(),
    status: (["pending", "responded"] as const)[i % 2],
    urgency_score: Math.floor(Math.random() * 10),
    post_url: null,
    external_id: null,
    response: i % 2 === 1 ? "Thank you for reaching out!" : null,
    responded_at: i % 2 === 1 ? daysAgo(i * 0.5) : null,
    metadata: null,
    parent_interaction_id: null,
    assigned_to: null,
    reply_count: i % 2 === 1 ? 1 : 0,
    resolved: i % 2 === 1,
    resolved_at: i % 2 === 1 ? daysAgo(i * 0.5) : null,
    resolved_by: null,
    created_at: daysAgo(i * 0.5 + 1),
    updated_at: daysAgo(i * 0.5 + 1),
  } as Interaction)),
];

// ─── DEMO REVIEWS ───────────────────────────────────────────────
export const DEMO_REVIEWS: Review[] = [
  {
    id: "demo-rev-1",
    user_id: "demo",
    reviewer_name: "Priya Sharma",
    reviewer_avatar: null,
    platform: "google",
    rating: 5,
    content: "Honestly impressed with the quality. Packaging was beautiful too — felt like opening a gift. Will be ordering again for sure!",
    response: null,
    responded_at: null,
    response_by: null,
    response_type: null,
    review_url: null,
    external_id: null,
    is_featured: false,
    created_at: hoursAgo(1),
    updated_at: hoursAgo(1),
  },
  {
    id: "demo-rev-2",
    user_id: "demo",
    reviewer_name: "Tom Nguyen",
    reviewer_avatar: null,
    platform: "google",
    rating: 2,
    content: "Order #4821 still hasn't arrived after 9 days. Tracking hasn't updated. Very disappointing for the price I paid.",
    response: null,
    responded_at: null,
    response_by: null,
    response_type: null,
    review_url: null,
    external_id: null,
    is_featured: false,
    created_at: hoursAgo(3),
    updated_at: hoursAgo(3),
  },
  {
    id: "demo-rev-3",
    user_id: "demo",
    reviewer_name: "David Park",
    reviewer_avatar: null,
    platform: "google",
    rating: 5,
    content: "Their team went above and beyond to fix my issue. Seriously the best customer service I've experienced in years.",
    response: "David, thank you for the kind words! We're thrilled we could help. Don't hesitate to reach out anytime!",
    responded_at: hoursAgo(5),
    response_by: null,
    response_type: "ai",
    review_url: null,
    external_id: null,
    is_featured: true,
    created_at: hoursAgo(6),
    updated_at: hoursAgo(5),
  },
  {
    id: "demo-rev-4",
    user_id: "demo",
    reviewer_name: "Alex Johnson",
    reviewer_avatar: null,
    platform: "facebook",
    rating: 1,
    content: "Terrible experience. Product broke after 2 days of normal use. I want a full refund immediately. Will not be ordering again.",
    response: null,
    responded_at: null,
    response_by: null,
    response_type: null,
    review_url: null,
    external_id: null,
    is_featured: false,
    created_at: hoursAgo(10),
    updated_at: hoursAgo(10),
  },
  {
    id: "demo-rev-5",
    user_id: "demo",
    reviewer_name: "Sophie Martin",
    reviewer_avatar: null,
    platform: "google",
    rating: 4,
    content: "Great product overall, though shipping was a bit slow. Quality is excellent — the materials feel premium. Would recommend to friends.",
    response: "Thanks Sophie! We appreciate the feedback on shipping — we're working on faster fulfillment options!",
    responded_at: daysAgo(1),
    response_by: null,
    response_type: "manual",
    review_url: null,
    external_id: null,
    is_featured: false,
    created_at: daysAgo(1.5),
    updated_at: daysAgo(1),
  },
  {
    id: "demo-rev-6",
    user_id: "demo",
    reviewer_name: "James Williams",
    reviewer_avatar: null,
    platform: "facebook",
    rating: 5,
    content: "Been a customer for 2 years now. Every single order has been perfect. These guys really care about quality.",
    response: "James, two years! We truly appreciate your loyalty. Thank you for being part of our community! 🙏",
    responded_at: daysAgo(2),
    response_by: null,
    response_type: "ai",
    review_url: null,
    external_id: null,
    is_featured: true,
    created_at: daysAgo(2.5),
    updated_at: daysAgo(2),
  },
  {
    id: "demo-rev-7",
    user_id: "demo",
    reviewer_name: "Aisha Khan",
    reviewer_avatar: null,
    platform: "google",
    rating: 3,
    content: "Product is decent but not worth the price tag. The competitor brand offers similar quality at 30% less. Might switch.",
    response: null,
    responded_at: null,
    response_by: null,
    response_type: null,
    review_url: null,
    external_id: null,
    is_featured: false,
    created_at: daysAgo(3),
    updated_at: daysAgo(3),
  },
  {
    id: "demo-rev-8",
    user_id: "demo",
    reviewer_name: "Ryan O'Brien",
    reviewer_avatar: null,
    platform: "google",
    rating: 5,
    content: "Ordered as a birthday gift and it arrived beautifully wrapped. My wife loved it! The attention to detail is incredible.",
    response: "That's wonderful to hear, Ryan! Happy birthday to your wife! 🎂 We're glad it made her day special.",
    responded_at: daysAgo(3.5),
    response_by: null,
    response_type: "ai",
    review_url: null,
    external_id: null,
    is_featured: false,
    created_at: daysAgo(4),
    updated_at: daysAgo(3.5),
  },
  {
    id: "demo-rev-9",
    user_id: "demo",
    reviewer_name: "Elena Vasquez",
    reviewer_avatar: null,
    platform: "facebook",
    rating: 4,
    content: "Love the sustainable packaging initiative! Product quality is great. Only wish there were more color options available.",
    response: null,
    responded_at: null,
    response_by: null,
    response_type: null,
    review_url: null,
    external_id: null,
    is_featured: false,
    created_at: daysAgo(5),
    updated_at: daysAgo(5),
  },
  {
    id: "demo-rev-10",
    user_id: "demo",
    reviewer_name: "Michael Chang",
    reviewer_avatar: null,
    platform: "google",
    rating: 5,
    content: "Fastest customer support response I've ever experienced. Had an issue and it was resolved within 30 minutes. Incredible.",
    response: "Speed is our commitment, Michael! We're glad we could resolve it quickly. Thanks for your patience!",
    responded_at: daysAgo(5.5),
    response_by: null,
    response_type: "ai",
    review_url: null,
    external_id: null,
    is_featured: true,
    created_at: daysAgo(6),
    updated_at: daysAgo(5.5),
  },
];

// ─── DEMO STREAMS ───────────────────────────────────────────────
export const DEMO_STREAMS: Stream[] = [
  {
    id: "demo-stream-1",
    user_id: "demo",
    name: "🔥 Urgent",
    platform: null,
    interaction_types: null,
    filters: { minUrgency: 7 },
    color: "#ef4444",
    position: 0,
    sidebar_position: 0,
    is_collapsed: false,
    notifications_enabled: true,
    notifications_muted: false,
    show_ai_suggestions: true,
    auto_sort_by_urgency: true,
    unread_count: 3,
    last_read_at: null,
    connected_platform_id: null,
    team_id: null,
    created_at: daysAgo(30),
    updated_at: hoursAgo(1),
  },
  {
    id: "demo-stream-2",
    user_id: "demo",
    name: "Instagram",
    platform: "instagram",
    interaction_types: null,
    filters: null,
    color: "#E4405F",
    position: 1,
    sidebar_position: 1,
    is_collapsed: false,
    notifications_enabled: true,
    notifications_muted: false,
    show_ai_suggestions: true,
    auto_sort_by_urgency: false,
    unread_count: 4,
    last_read_at: null,
    connected_platform_id: null,
    team_id: null,
    created_at: daysAgo(30),
    updated_at: hoursAgo(2),
  },
  {
    id: "demo-stream-3",
    user_id: "demo",
    name: "Google Reviews",
    platform: "google",
    interaction_types: ["review"],
    filters: null,
    color: "#ea4335",
    position: 2,
    sidebar_position: 2,
    is_collapsed: false,
    notifications_enabled: true,
    notifications_muted: false,
    show_ai_suggestions: true,
    auto_sort_by_urgency: false,
    unread_count: 2,
    last_read_at: null,
    connected_platform_id: null,
    team_id: null,
    created_at: daysAgo(30),
    updated_at: hoursAgo(3),
  },
  {
    id: "demo-stream-4",
    user_id: "demo",
    name: "Facebook",
    platform: "facebook",
    interaction_types: null,
    filters: null,
    color: "#1877F2",
    position: 3,
    sidebar_position: 3,
    is_collapsed: false,
    notifications_enabled: true,
    notifications_muted: false,
    show_ai_suggestions: true,
    auto_sort_by_urgency: false,
    unread_count: 2,
    last_read_at: null,
    connected_platform_id: null,
    team_id: null,
    created_at: daysAgo(30),
    updated_at: hoursAgo(4),
  },
  {
    id: "demo-stream-5",
    user_id: "demo",
    name: "😊 Positive Mentions",
    platform: null,
    interaction_types: null,
    filters: { sentiment: "positive" },
    color: "#10b981",
    position: 4,
    sidebar_position: 4,
    is_collapsed: false,
    notifications_enabled: false,
    notifications_muted: true,
    show_ai_suggestions: false,
    auto_sort_by_urgency: false,
    unread_count: 5,
    last_read_at: null,
    connected_platform_id: null,
    team_id: null,
    created_at: daysAgo(30),
    updated_at: hoursAgo(5),
  },
];

/**
 * Filter demo interactions to match a stream's filters (mirrors useStreamInteractions logic)
 */
export function filterDemoInteractionsForStream(stream: Stream): Interaction[] {
  return DEMO_INTERACTIONS.filter((interaction) => {
    // Platform filter
    if (stream.platform && stream.platform !== "all" && interaction.platform !== stream.platform) {
      return false;
    }

    // Interaction type filter
    if (stream.interaction_types && stream.interaction_types.length > 0) {
      const typeMapping: Record<string, string> = {
        comment: "comment",
        message: "dm",
        review: "review",
        mention: "mention",
      };
      const mappedTypes = stream.interaction_types.map((t) => typeMapping[t] || t);
      if (!mappedTypes.includes(interaction.interaction_type)) {
        return false;
      }
    }

    // JSONB filters
    const filters = (stream.filters as Record<string, any>) || {};

    if (filters.sentiment && interaction.sentiment !== filters.sentiment) {
      return false;
    }

    if (filters.status && interaction.status !== filters.status) {
      return false;
    }

    if (filters.minUrgency && (interaction.urgency_score || 0) < filters.minUrgency) {
      return false;
    }

    return true;
  });
}
